/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ManagerIndexImport } from './routes/manager/index'
import { Route as CustomerIndexImport } from './routes/customer/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ManagerIndexRoute = ManagerIndexImport.update({
  path: '/manager/',
  getParentRoute: () => rootRoute,
} as any)

const CustomerIndexRoute = CustomerIndexImport.update({
  path: '/customer/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerIndexImport
      parentRoute: typeof rootRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customer' | '/manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customer' | '/manager'
  id: '__root__' | '/' | '/customer/' | '/manager/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/customer/",
        "/manager/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/customer/": {
      "filePath": "customer/index.tsx"
    },
    "/manager/": {
      "filePath": "manager/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
